name: Run Tests on PR

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    name: Build and run tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy env vars
        run: cp .env.local.example .env

      - uses: hoverkraft-tech/compose-action@v2.0.0

      - name: Install deps
        run: |
          docker compose exec laravel.test composer install
          docker compose exec laravel.test npm ci

      # - name: Cache dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: /tmp/composer-cache
      #     key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
      #     restore-keys: ${{ runner.os }}-composer-

      - name: Initialize project
        run: |
          # sudo chmod -R 775 *
          docker compose exec laravel.test php artisan key:generate
          docker compose exec laravel.test php artisan migrate


      - name: Run tests
        run: |
          docker compose exec laravel.test php artisan test
