name: Run Tests on PR

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    name: Build and run tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List filesystem contents
        run: |
          ls -alh
          ls -alh /home/runner/work/microtube/microtube

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        env:
          fail-fast: true
        with:
          php-version: '8.3.11'

      - name: Copy env vars
        run: cp .env.local.example .env

      # Remove caching for now because it breaks the CI for some reason
      # - name: Cache dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: /tmp/composer-cache
      #     key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
      #     restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_extensions: exif

      - uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Initialize project
        run: |
          sudo chmod -R 775 *
          php artisan key:generate
          php artisan migrate


      - name: Run tests
        run: |
          sudo php artisan test
